apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: vijayarajr/nodejsapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          value: postgres  # Replace with actual username
        - name: POSTGRES_PASSWORD
          value: redhat  # Replace with actual password
        - name: POSTGRES_HOST
          # value: "postgres-service"  # Assuming service name for PostgreSQL
        - name: POSTGRES_PORT
          value: 5432
      restartPolicy: Always

