apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
  - protocol: TCP
    port: 80  # External port for accessing the Node.js application
    targetPort: 8080  # Maps to the container port
  type: NodePort  # Expose the service through a NodePort

